name = "PrimeNumberTheoremAnd"
defaultTargets = ["PrimeNumberTheoremAnd"]

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false
autoImplicit = false
relaxedAutoImplicit = false
linter.mathlibStandardSet = true
linter.style.openClassical = false
linter.style.longLine = false
linter.style.emptyLine = false
linter.flexible = true

[[require]]
name = "LeanArchitect"
git = "https://github.com/hanwenzhu/LeanArchitect.git"
rev = "v4.28.0-rc1"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "leancert"
git = "https://github.com/alerad/leancert"
rev = "v4.28.0-rc1"

[[lean_lib]]
name = "PrimeNumberTheoremAnd"
