name = "PrimeNumberTheoremAnd"
defaultTargets = ["PrimeNumberTheoremAnd"]

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.openClassical = false
weak.linter.style.longLine = false
weak.linter.style.emptyLine = false
weak.linter.flexible = true

[[require]]
name = "LeanArchitect"
git = "https://github.com/hanwenzhu/LeanArchitect.git"
rev = "v4.27.0-rc1"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "PrimeNumberTheoremAnd"
